

INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, true, true, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, true, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, true, true, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, false, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, false, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, false, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, false, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, false, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, false, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, false, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, false, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, false, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, false, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, false, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, false, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, false, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, false, true, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, false, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, false, true, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, true, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, true, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, true, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, true, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, true, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, true, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, true, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, true, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, true, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, true, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, true, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, true, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, true, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', false, true, true, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, true, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'Microwave/Bluetooth', true, true, true, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, true, 'Surface/Suspension/Continuous', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST4FT40WT-35G5K-[blank, EM, MS, ES]', '4ft', '24w/32w/40w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3120/4160/5200LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$15.96 (DDP)', '$16.10 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');