

INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2225-J-H', '2x2 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$16.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2225-J-H', '2x2 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$16.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2225-J-H', '2x2 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$16.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2225-J-H', '2x2 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$16.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2225-J-H', '2x2 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$16.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2225-J-H', '2x2 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$16.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2472-J-H', '2x4 ft', '40/45/50W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '6000/6750/7500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$26.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2472-J-H', '2x4 ft', '40/45/50W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '6000/6750/7500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$26.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2472-J-H', '2x4 ft', '40/45/50W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '6000/6750/7500LM', '150lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$26.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2472-J-H', '2x4 ft', '40/45/50W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '6000/6750/7500LM', '150lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$26.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2472-J-H', '2x4 ft', '40/45/50W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '6000/6750/7500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$26.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2472-J-H', '2x4 ft', '40/45/50W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '6000/6750/7500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$26.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2472-J-H', '2x4 ft', '40/45/50W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '6000/6750/7500LM', '150lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$26.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU2472-J-H', '2x4 ft', '40/45/50W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '6000/6750/7500LM', '150lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$26.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU1440-J-H', '1x4 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$17.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU1440-J-H', '1x4 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$17.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU1440-J-H', '1x4 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$17.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU1440-J-H', '1x4 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$17.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU1440-J-H', '1x4 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$17.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU1440-J-H', '1x4 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave/Bluetooth', 'none,Cellular', false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$17.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU1440-J-H', '1x4 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$17.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'SL-PBU1440-J-H', '1x4 ft', '21/25/30W', 'AC120-277Vac', '3/4/5k, Tunable', '80', '3150/3750/4500LM', '150lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1ZMfBqg34LqqYbi6vsNdZ9fLOwr69atYd/view?usp=drive_link', '5 Yr', '5,000', '$17.20', 'https://drive.google.com/file/d/1b6OYYk4De9cy8Y4UIbsMsIEcjtABkD2A/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2240WT-3545K', '2x2 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$17.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2240WT-3545K', '2x2 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$17.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2240WT-3545K', '2x2 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$17.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2240WT-3545K', '2x2 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$17.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2240WT-3545K', '2x2 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$17.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2240WT-3545K', '2x2 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$17.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2240WT-3545K', '2x2 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$17.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2240WT-3545K', '2x2 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$17.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2450WT-3545K', '2x4 ft', '25/30/35/40/50W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '3625/4350/5075/5800/7975LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2450WT-3545K', '2x4 ft', '25/30/35/40/50W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '3625/4350/5075/5800/7975LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2450WT-3545K', '2x4 ft', '25/30/35/40/50W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '3625/4350/5075/5800/7975LM', '145lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2450WT-3545K', '2x4 ft', '25/30/35/40/50W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '3625/4350/5075/5800/7975LM', '145lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2450WT-3545K', '2x4 ft', '25/30/35/40/50W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '3625/4350/5075/5800/7975LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2450WT-3545K', '2x4 ft', '25/30/35/40/50W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '3625/4350/5075/5800/7975LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2450WT-3545K', '2x4 ft', '25/30/35/40/50W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '3625/4350/5075/5800/7975LM', '145lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP2450WT-3545K', '2x4 ft', '25/30/35/40/50W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '3625/4350/5075/5800/7975LM', '145lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP1440WT-3545K', '1x4 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP1440WT-3545K', '1x4 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP1440WT-3545K', '1x4 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP1440WT-3545K', '1x4 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', false, false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP1440WT-3545K', '1x4 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', false, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP1440WT-3545K', '1x4 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', false, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP1440WT-3545K', '1x4 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', true, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'DM-BLP1440WT-3545K', '1x4 ft', '20/25/30/35/40W selectable', 'AC120-277Vac', '3/3.5/4/5k, Tunable', '80', '2900/3625/4350/5075/5800LM', '145lm/w', '0-10V', 'White/Metal', false, true, 'Recessed/Surface/Suspended', false, 'ETL DLC Premium', '85 days', 'https://drive.google.com/file/d/1LKvz-CnTznfMiLV8zRVJF5LrqoJYSM9t/view?usp=drive_link', '5 Yr', 'TBN', '$24.90 (DDP)', 'https://drive.google.com/file/d/1Bxi8fsIhzDYHJpjOtj7NBl9cw9tkwpGJ/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'AL-LT-0606-40W-HDNA-TWTC', '2x2 ft', '40/36/30/25/20W', 'AC100-277V', '3.5/4.1/5k, Tunable', '82', '5000/4500/3750/3125/2500LM', '125lm/w', false, 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', true, 'Recessed/Surface/Suspended', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1neVUKHD_-jXPawSMewitHIG6xzs6fg8l/view?usp=drive_link', '5 Yr', '2,000', '$11.45 (Donguan)', 'https://drive.google.com/file/d/1FBrV7DrKhqbI7MOQEPgkOWyFhjSkZqTv/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'AL-LT-0606-40W-HDNA-TWTC', '2x2 ft', '40/36/30/25/20W', 'AC100-277V', '3.5/4.1/5k, Tunable', '82', '5000/4500/3750/3125/2500LM', '125lm/w', false, 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', true, 'Recessed/Surface/Suspended', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1neVUKHD_-jXPawSMewitHIG6xzs6fg8l/view?usp=drive_link', '5 Yr', '2,000', '$11.45 (Donguan)', 'https://drive.google.com/file/d/1FBrV7DrKhqbI7MOQEPgkOWyFhjSkZqTv/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'AL-LT-0606-40W-HDNA-TWTC', '2x2 ft', '40/36/30/25/20W', 'AC100-277V', '3.5/4.1/5k, Tunable', '82', '5000/4500/3750/3125/2500LM', '125lm/w', false, 'White/Metal', false, false, 'Recessed/Surface/Suspended', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1neVUKHD_-jXPawSMewitHIG6xzs6fg8l/view?usp=drive_link', '5 Yr', '2,000', '$11.45 (Donguan)', 'https://drive.google.com/file/d/1FBrV7DrKhqbI7MOQEPgkOWyFhjSkZqTv/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'AL-LT-0606-40W-HDNA-TWTC', '2x2 ft', '40/36/30/25/20W', 'AC100-277V', '3.5/4.1/5k, Tunable', '82', '5000/4500/3750/3125/2500LM', '125lm/w', false, 'White/Metal', false, false, 'Recessed/Surface/Suspended', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1neVUKHD_-jXPawSMewitHIG6xzs6fg8l/view?usp=drive_link', '5 Yr', '2,000', '$11.45 (Donguan)', 'https://drive.google.com/file/d/1FBrV7DrKhqbI7MOQEPgkOWyFhjSkZqTv/view?usp=sharing');