

INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-224-I', '2ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3600LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, true, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, true, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, true, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, true, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, true, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');