

INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR14-22WCCT', '14"', '22W', 'AC120V', '2.7-6.5k, Tunable', '80', '1760lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$8.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR16-26WCCT', '16"', '26W', 'AC120V', '2.7-6.5k, Tunable', '80', '2080lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '9.90(Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', false, false, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', false, true, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', false, true, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', false, false, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', false, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', true, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', true, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', false, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', false, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', true, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', true, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-2FT-LS100-20W3CCT', '2ft', '20W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', false, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$9.80 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', false, false, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', false, true, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', false, true, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');