

INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'AL-LT-0606-40W-HDNA-TWTC', '2x2 ft', '40/36/30/25/20W', 'AC100-277V', '3.5/4.1/5k, Tunable', '82', '5000/4500/3750/3125/2500LM', '125lm/w', false, 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', false, 'Recessed/Surface/Suspended', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1neVUKHD_-jXPawSMewitHIG6xzs6fg8l/view?usp=drive_link', '5 Yr', '2,000', '$11.45 (Donguan)', 'https://drive.google.com/file/d/1FBrV7DrKhqbI7MOQEPgkOWyFhjSkZqTv/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'AL-LT-0606-40W-HDNA-TWTC', '2x2 ft', '40/36/30/25/20W', 'AC100-277V', '3.5/4.1/5k, Tunable', '82', '5000/4500/3750/3125/2500LM', '125lm/w', false, 'White/Metal', 'Occupancy', 'PIR/Microwave', 'none,yes', false, 'Recessed/Surface/Suspended', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1neVUKHD_-jXPawSMewitHIG6xzs6fg8l/view?usp=drive_link', '5 Yr', '2,000', '$11.45 (Donguan)', 'https://drive.google.com/file/d/1FBrV7DrKhqbI7MOQEPgkOWyFhjSkZqTv/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'AL-LT-0606-40W-HDNA-TWTC', '2x2 ft', '40/36/30/25/20W', 'AC100-277V', '3.5/4.1/5k, Tunable', '82', '5000/4500/3750/3125/2500LM', '125lm/w', false, 'White/Metal', false, true, 'Recessed/Surface/Suspended', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1neVUKHD_-jXPawSMewitHIG6xzs6fg8l/view?usp=drive_link', '5 Yr', '2,000', '$11.45 (Donguan)', 'https://drive.google.com/file/d/1FBrV7DrKhqbI7MOQEPgkOWyFhjSkZqTv/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'AL-LT-0606-40W-HDNA-TWTC', '2x2 ft', '40/36/30/25/20W', 'AC100-277V', '3.5/4.1/5k, Tunable', '82', '5000/4500/3750/3125/2500LM', '125lm/w', false, 'White/Metal', false, true, 'Recessed/Surface/Suspended', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1neVUKHD_-jXPawSMewitHIG6xzs6fg8l/view?usp=drive_link', '5 Yr', '2,000', '$11.45 (Donguan)', 'https://drive.google.com/file/d/1FBrV7DrKhqbI7MOQEPgkOWyFhjSkZqTv/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-440L', '4ft', '25/35/50W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3250/4550/6500LM', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', false, true, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$38.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-440L', '4ft', '25/35/50W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3250/4550/6500LM', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', false, false, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$38.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-440L', '4ft', '25/35/50W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3250/4550/6500LM', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', 'Occupancy', 'PIR', true, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$38.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-440L', '4ft', '25/35/50W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3250/4550/6500LM', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', 'Occupancy', 'PIR', false, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$38.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-64W-8ft', '8ft', '64W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '8320lm', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', false, true, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$78.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-64W-8ft', '8ft', '64W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '8320lm', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', false, false, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$78.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-64W-8ft', '8ft', '64W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '8320lm', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', 'Occupancy', 'PIR', true, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$78.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-64W-8ft', '8ft', '64W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '8320lm', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', 'Occupancy', 'PIR', false, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$78.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-80W-8ft', '8ft', '80W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '10400lm', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', false, true, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$78.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-80W-8ft', '8ft', '80W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '10400lm', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', false, false, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$78.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-80W-8ft', '8ft', '80W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '10400lm', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', 'Occupancy', 'PIR', true, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$78.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Linear Light', 'SL-SFH-80W-8ft', '8ft', '80W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '10400lm', '130lm/w', '0-10v', 'White/Metal/Stanless Steel', 'Occupancy', 'PIR', false, 'Surface/Suspension', 'DLC UL', '85 days', 'https://drive.google.com/file/d/14nRbHDkiSx-ZdEgdZu0x2M_LPxGkA-vG/view?usp=drive_link', '5 year', '5000', '$78.00(DDP USA)', 'https://drive.google.com/file/d/1nkgSHD99CfFV_T4ldUXiR6I9vKfpv7ux/view?usp=sharing', 'IP65 and IK08');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT12/24/32W-354050K', '4ft', '12W/24W/32W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1920/3840/5120LM', '160lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$24.50 (DDP)', '$24.87(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT12/24/32W-354050K', '4ft', '12W/24W/32W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1920/3840/5120LM', '160lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$24.50 (DDP)', '$24.87(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT12/24/32W-354050K', '4ft', '12W/24W/32W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1920/3840/5120LM', '160lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$24.50 (DDP)', '$24.87(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT12/24/32W-354050K', '4ft', '12W/24W/32W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1920/3840/5120LM', '160lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$24.50 (DDP)', '$24.87(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT12/24/32W-354050K', '4ft', '12W/24W/32W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1920/3840/5120LM', '160lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$24.50 (DDP)', '$24.87(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT12/24/32W-354050K', '4ft', '12W/24W/32W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1920/3840/5120LM', '160lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$24.50 (DDP)', '$24.87(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT12/24/32W-354050K', '4ft', '12W/24W/32W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1920/3840/5120LM', '160lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$24.50 (DDP)', '$24.87(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT12/24/32W-354050K', '4ft', '12W/24W/32W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1920/3840/5120LM', '160lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$24.50 (DDP)', '$24.87(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT24/40/55W-354050K', '8ft', '24W/40W/55W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3840/6400/8800LM', '160lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$35.50 (DDP)', '$35.95(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT24/40/55W-354050K', '8ft', '24W/40W/55W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3840/6400/8800LM', '160lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$35.50 (DDP)', '$35.95(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT24/40/55W-354050K', '8ft', '24W/40W/55W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3840/6400/8800LM', '160lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$35.50 (DDP)', '$35.95(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT24/40/55W-354050K', '8ft', '24W/40W/55W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3840/6400/8800LM', '160lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$35.50 (DDP)', '$35.95(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT24/40/55W-354050K', '8ft', '24W/40W/55W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3840/6400/8800LM', '160lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$35.50 (DDP)', '$35.95(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT24/40/55W-354050K', '8ft', '24W/40W/55W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3840/6400/8800LM', '160lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$35.50 (DDP)', '$35.95(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT24/40/55W-354050K', '8ft', '24W/40W/55W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3840/6400/8800LM', '160lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$35.50 (DDP)', '$35.95(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT24/40/55W-354050K', '8ft', '24W/40W/55W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3840/6400/8800LM', '160lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1sfvU-AsHKzduog0ebgkylf5fx76wEQd1/view?usp=drive_link', '5 year', 'TBN', '$35.50 (DDP)', '$35.95(DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP2FT25WT-3545k', '2ft', '15W/20W/25W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '2250/3000/3750LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$17.35 (DDP)', '$18.11 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP2FT25WT-3545k', '2ft', '15W/20W/25W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '2250/3000/3750LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$17.35 (DDP)', '$18.11 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP2FT25WT-3545k', '2ft', '15W/20W/25W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '2250/3000/3750LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$17.35 (DDP)', '$18.11 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP2FT25WT-3545k', '2ft', '15W/20W/25W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '2250/3000/3750LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$17.35 (DDP)', '$18.11 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP2FT25WT-3545k', '2ft', '15W/20W/25W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '2250/3000/3750LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$17.35 (DDP)', '$18.11 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP2FT25WT-3545k', '2ft', '15W/20W/25W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '2250/3000/3750LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$17.35 (DDP)', '$18.11 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP2FT25WT-3545k', '2ft', '15W/20W/25W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '2250/3000/3750LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$17.35 (DDP)', '$18.11 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP2FT25WT-3545k', '2ft', '15W/20W/25W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '2250/3000/3750LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$17.35 (DDP)', '$18.11 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT45WT-3545k', '4ft', '25W/35W/45W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3750/5250/6750LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$26.48 (DDP)', '$27.32 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT45WT-3545k', '4ft', '25W/35W/45W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3750/5250/6750LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$26.48 (DDP)', '$27.32 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT45WT-3545k', '4ft', '25W/35W/45W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3750/5250/6750LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$26.48 (DDP)', '$27.32 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT45WT-3545k', '4ft', '25W/35W/45W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3750/5250/6750LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$26.48 (DDP)', '$27.32 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT45WT-3545k', '4ft', '25W/35W/45W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3750/5250/6750LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$26.48 (DDP)', '$27.32 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT45WT-3545k', '4ft', '25W/35W/45W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3750/5250/6750LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$26.48 (DDP)', '$27.32 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT45WT-3545k', '4ft', '25W/35W/45W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3750/5250/6750LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$26.48 (DDP)', '$27.32 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP4FT45WT-3545k', '4ft', '25W/35W/45W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '3750/5250/6750LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$26.48 (DDP)', '$27.32 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT80WT-3545k', '8ft', '50W/65W/80W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '7500/9750/12000LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT80WT-3545k', '8ft', '50W/65W/80W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '7500/9750/12000LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');