

INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL14IN24W5CCT', '14''''', '20W', 'AC120V', '2.7-5k, Tunable', '80', '1500lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', false, false, false, false, 'Surface', 'ETL DLC Premium T24', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', false, false, true, false, 'Surface', 'ETL DLC Premium T24', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', false, false, false, true, 'Surface', 'ETL DLC Premium T24', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', false, true, false, false, 'Surface', 'ETL DLC Premium T24', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', false, false, true, true, 'Surface', 'ETL DLC Premium T24', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', false, true, true, false, 'Surface', 'ETL DLC Premium T24', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', false, true, false, true, 'Surface', 'ETL DLC Premium T24', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', false, true, true, true, 'Surface', 'ETL DLC Premium T24', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, false, false, 'Surface', 'ETL DLC Premium T24', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, true, false, 'Surface', 'ETL DLC Premium T25', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, false, true, 'Surface', 'ETL DLC Premium T26', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, false, false, 'Surface', 'ETL DLC Premium T27', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, true, true, 'Surface', 'ETL DLC Premium T28', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, true, false, 'Surface', 'ETL DLC Premium T29', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, false, true, 'Surface', 'ETL DLC Premium T30', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-DLMS20WT-2733545K', '14''''', '20/25/30/35W', 'AC120V', '2.7-5k, Tunable', '80', '2800lm', '140lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, true, true, 'Surface', 'ETL DLC Premium T31', '75 days', 'https://drive.google.com/file/d/1-hSsZaxS7_qsovIE3FLgM2N21_gZkL6P/view?usp=drive_link', '5 Yr', '2,000', '$36.00(DDP)', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, false, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', false, true, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, true, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, false, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', true, false, false, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'ARVL-HY-DR12-16WCCT', '12"', '16W', 'AC120V', '2.7-6.5k, Tunable', '80', '1280lm', '80lm/w', 'Triac', 'Stainless Steel/Metal', 'B-Level', 'PIR', false, true, true, 'Surface', 'ETL T24', '85 days', 'https://drive.google.com/file/d/1yxy0epeKUREcIq-_pfBufKJYjH2DDVfh/view?usp=drive_link', '5 Yr', '1,000', '$6.70 (Ningbo)', 'https://drive.google.com/file/d/1R9xLBl5K1zddCLbexUsM2TqapYdFLjca/view?usp=sharing');