INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'FXF01185E-7A5T90W', '4''''', '7.5W', 'AC120V', '2.7-5k, Tunable', '80', '615lm', '82lm/w', '0-10V', 'White-Aluminum', false, 'Recessed', 'ETL DLC FCC ES T24 CP65', '75 days', 'https://drive.google.com/file/d/1bc-40WJFu2nKs0LR9NxoweTLGURpR1ds/view?usp=drive_link', '5 Yr', '5,000', '2.94 (Ningbo)', '$3.46', 'https://drive.google.com/file/d/1Bx8POa0xVolFubzCy_06HO1FOmFiFNHH/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'FXF01185E-9A5T90W', '4''''', '9W', 'AC120V', '2.7-5k, Tunable', '80', '738lm', '82lm/w', '0-10V', 'White-Aluminum', false, 'Recessed', 'ETL DLC FCC ES T24 CP65', '75 days', 'https://drive.google.com/file/d/1bc-40WJFu2nKs0LR9NxoweTLGURpR1ds/view?usp=drive_link', '5 Yr', '5,000', '2.94 (Ningbo)', '$3.46', 'https://drive.google.com/file/d/1Bx8POa0xVolFubzCy_06HO1FOmFiFNHH/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'FXF01185E-12A5T90W', '6''''', '12W', 'AC120V', '2.7-5k, Tunable', '80', '984lm', '82lm/w', '0-10V', 'White-Aluminum', false, 'Recessed', 'ETL DLC FCC ES T24 CP66', '75 days', 'https://drive.google.com/file/d/1bc-40WJFu2nKs0LR9NxoweTLGURpR1ds/view?usp=drive_link', '5 Yr', '5,000', '3.90 (Ningbo)', '$4.59', 'https://drive.google.com/file/d/1Bx8POa0xVolFubzCy_06HO1FOmFiFNHH/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'FXF01185E-17A5T90W', '8''''', '17W', 'AC120V', '2.7-5k, Tunable', '80', '1394lm', '82lm/w', '0-10V', 'White-Aluminum', false, 'Recessed', 'ETL DLC FCC ES T24 CP67', '75 days', 'https://drive.google.com/file/d/1bc-40WJFu2nKs0LR9NxoweTLGURpR1ds/view?usp=drive_link', '5 Yr', '5,000', '5.88 (Ningbo)', '$6.92', 'https://drive.google.com/file/d/1Bx8POa0xVolFubzCy_06HO1FOmFiFNHH/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'FXF01185E-18A5T90W', '8''''', '18W', 'AC120V', '2.7-5k, Tunable', '80', '1476lm', '82lm/w', '0-10V', 'White-Aluminum', false, 'Recessed', 'ETL DLC FCC ES T24 CP67', '75 days', 'https://drive.google.com/file/d/1bc-40WJFu2nKs0LR9NxoweTLGURpR1ds/view?usp=drive_link', '5 Yr', '5,000', '5.88 (Ningbo)', '$6.92', 'https://drive.google.com/file/d/1Bx8POa0xVolFubzCy_06HO1FOmFiFNHH/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'HS-STC509WH', '4"', '9W', 'AC110-130V', '2.7-5k, Tunable', '80', '720lm', '70-90lm/W', 'Triac', 'White-Aluminum', false, 'Recessed', 'ETL ES FCC', '75 days', 'https://docs.google.com/spreadsheets/d/1c5IZBxwWOWWz-l0IuT3zEqp942sRIsd5/edit?usp=drive_link&ouid=108502356149815945805&rtpof=true&sd=true', '3 Yr', '5,000', '$2.34', 'https://drive.google.com/file/d/1f6iggBDm6UddmfZxn5ZNWnw8KR9dkUQC/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'HS-STC515WH', '6"', '15W', 'AC110-130V', '2.7-5k, Tunable', '80', '1200lm', '70-90lm/W', 'Triac', 'White-Aluminum', false, 'Recessed', 'ETL ES FCC', '75 days', 'https://docs.google.com/spreadsheets/d/1c5IZBxwWOWWz-l0IuT3zEqp942sRIsd5/edit?usp=drive_link&ouid=108502356149815945805&rtpof=true&sd=true', '3 Yr', '5,000', '$3.01', 'https://drive.google.com/file/d/1f6iggBDm6UddmfZxn5ZNWnw8KR9dkUQC/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'HS-STC518WH', '8"', '18W', 'AC110-130V', '2.7-5k, Tunable', '80', '1440lm', '70-90lm/W', 'Triac', 'White-Aluminum', false, 'Recessed', 'ETL ES FCC', '75 days', 'https://docs.google.com/spreadsheets/d/1c5IZBxwWOWWz-l0IuT3zEqp942sRIsd5/edit?usp=drive_link&ouid=108502356149815945805&rtpof=true&sd=true', '3 Yr', '5,000', '$3.95', 'https://drive.google.com/file/d/1f6iggBDm6UddmfZxn5ZNWnw8KR9dkUQC/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'ARVL-HY-USDL-R4-9W-5CCT', '4"', '9W', 'AC120', '2.7-5k, Tunable', '80', '700lm', '70-90lm/W', 'Triac', 'White/Nickle/Black-Aluminum', false, 'Recessed', 'ETL ES FCC', '75 days', 'https://drive.google.com/file/d/1-aRBlFTfv5kaE94gUsClWAJk0Wu0Ha_8/view?usp=drive_link', '5 Yr', '1,000', '$2.05', 'https://drive.google.com/file/d/1VJyr0VPRS4Jp7sqdVjfg6et2QPEdxcyx/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'ARVL-HY-USDL-R6-12W-5CCT', '6"', '12W', 'AC120', '2.7-5k, Tunable', '80', '900lm', '70-90lm/W', 'Triac', 'White/Nickle/Black-Aluminum', false, 'Recessed', 'ETL ES FCC', '75 days', 'https://drive.google.com/file/d/1-aRBlFTfv5kaE94gUsClWAJk0Wu0Ha_8/view?usp=drive_link', '5 Yr', '1,000', '$2.75', 'https://drive.google.com/file/d/1VJyr0VPRS4Jp7sqdVjfg6et2QPEdxcyx/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, remote_control, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_thailand_vietnam, photo) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'Special Order (Keep on list or not?)', '8"', '18W', 'AC120', '2.7-5k, Tunable', '80', '1440lm', '70-90lm/W', 'Triac', 'White/Nickle/Black-Aluminum', false, 'Recessed', 'ETL ES FCC', '75 days', 'https://drive.google.com/file/d/1-aRBlFTfv5kaE94gUsClWAJk0Wu0Ha_8/view?usp=drive_link', '5 Yr', '1,000', '$6.50', 'https://drive.google.com/file/d/1VJyr0VPRS4Jp7sqdVjfg6et2QPEdxcyx/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, remote_control, mounting, certifications, lead_time, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'PVDL-PLA02-8WE', '4"', '8W', 'AC120v', '3-6.5k, Tunable', '80', '800lm', '100lm/w', 'Triac', false, 'Recessed', 'ETL ES FCC', '75 days', '5 Yr', '5,000', '$2.98', '$2.98 (Vietnam)');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, remote_control, mounting, certifications, lead_time, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam) VALUES ('LED Downlight Series', 'LED Ultra Slim Downlight', 'PVDL-PLA02-12WG', '6"', '12W', 'AC120v', '3-6.5k, Tunable', '80', '1200lm', '100lm/w', 'Triac', false, 'Recessed', 'ETL ES FCC', '75 days', '5 Yr', '5,000', '$3.40', '$3.40 (Vietnam)');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23001', '10''''', '8/12/16W', 'AC120V', '2.7-5k, Tunable', '80', '1200lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', false, 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$6.60 (Ningbo)', '$7.76', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23001', '10''''', '8/12/16W', 'AC120V', '2.7-5k, Tunable', '80', '1200lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$6.60 (Ningbo)', '$7.76', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23002', '12''''', '8/12/16W', 'AC120V', '2.7-5k, Tunable', '80', '1200lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', false, 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$8.20 (Ningbo)', '$9.65', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23002', '12''''', '8/12/16W', 'AC120V', '2.7-5k, Tunable', '80', '1200lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$8.20 (Ningbo)', '$9.65', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23003', '14"', '12/16/22W', 'AC120V', '2.7-5k, Tunable', '80', '1650lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', false, 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$9.40 (Ningbo)', '$11.06', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23003', '14"', '12/16/22W', 'AC120V', '2.7-5k, Tunable', '80', '1650lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$9.40 (Ningbo)', '$11.06', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23004', '16''''', '16/22/30W', 'AC120V', '2.7-5k, Tunable', '80', '2250lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', false, 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$8.20 (Ningbo)', '$9.65', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23004', '16''''', '16/22/30W', 'AC120V', '2.7-5k, Tunable', '80', '2250lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$8.20 (Ningbo)', '$9.65', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23005', '18''''', '22/30/36W', 'AC120V', '2.7-5k, Tunable', '80', '2700lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', false, 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$9.40 (Ningbo)', '$11.06', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, mounting, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'FXF23005', '18''''', '22/30/36W', 'AC120V', '2.7-5k, Tunable', '80', '2700lm', '100lm/w  75lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', 'Surface', 'ETL', '75 days', 'https://drive.google.com/file/d/1YAiWD2O-dyXLp8q6CwM4usEu2_MSVSY7/view?usp=drive_link', '5 Yr', '5,000', '$9.40 (Ningbo)', '$11.06', 'https://drive.google.com/file/d/1w_zTun0PWcXvB0SWsONtUQcs8Kv-4sWd/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL10IN16W5CCT', '10''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1120lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', true, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, false, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', false, true, true, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, false, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, true, false, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, mounting, certifications, lead_time, cut_sheet, warranty, moq, photo) VALUES ('LED Flush Mount Light', 'LED Double Ring Ceiling Light', 'DM-CL12IN20W5CCT', '12''''', '16W', 'AC120V', '2.7-5k, Tunable', '80', '1400lm', '70lm/w', 'Triac', 'Brush Nickel/Metal', 'B-Level', 'PIR', false, false, true, 'Surface', 'ETL T24', '75 days', 'https://drive.google.com/file/d/1IjSMBWujd7BkgZvzmfSjgLYArSJZYIVy/view?usp=drive_link', '5 Yr', '2,000', 'https://drive.google.com/file/d/1HAQ1Iucv7BC33ha5qeNLEMKZjthzdT4j/view?usp=sharing');