

INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, true, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, true, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, true, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, true, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, true, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, true, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, true, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, true, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, false, true, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, true, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', false, true, true, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, false, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, false, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, false, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, false, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, false, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, false, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, true, false, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, true, false, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', false, true, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, true, true, 'Surface/Suspension/Continuous', 'no kit', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED Linear Series', 'Strip Light', 'SL-ST-440-I', '4ft', '22W/28W/34W/40W', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '6000LM', '150lm/w', '0-10V', 'White/Metal/PVC', 'Occupancy', 'PIR/Bluetooth', true, true, true, true, 'Surface/Suspension/Continuous', 'Install Kit-V-Hook/Aircraft Cable/T-Bar bracket Option', 'UL DLC', '85 days', 'https://drive.google.com/file/d/1vJLtMQ50XKLwxPEX0Nvz1tm6kkxPCjkg/view?usp=drive_link', '5000', '$15.40', 'https://drive.google.com/file/d/1bB0fdFpQ1-fSLTmBGEb_LyIFEOMw73Of/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, material_finish, mounting, adjustment_dial, certifications, lead_time, cut_sheet, ip_rating) VALUES ('LED Linear Series', 'Light Tube T5', 'SL-DGA00-209LT-G5-H-U', '2ft', '9W', 'AC100-347Vac', '2700-6500k', '80', '1260lm', '140lm/w', 'White/A6063 Aluminum/PCB', 'Tube', 'Single or Double Input Optional', 'DLC UL RoHS, LM79, LM80', '75 days', 'https://drive.google.com/file/d/1PC1Z5duXbaOqFT0IDuXb0o0n6J1xX_kA/view?usp=drive_link', 'https://drive.google.com/file/d/1p--XO0qq1MZFB1gYsre6D4z9iUGNr3Dv/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, material_finish, mounting, adjustment_dial, certifications, lead_time, cut_sheet, ip_rating) VALUES ('LED Linear Series', 'Light Tube T5', 'SL-DGA00-415LT-G5-H-U', '4ft', '15W', 'AC100-347Vac', '2700-6500k', '80', '2100lm', '140lm/w', 'White/A6063 Aluminum/PCB', 'Tube', 'Single or Double Input Optional', 'DLC UL RoHS, LM79, LM80', '75 days', 'https://drive.google.com/file/d/1PC1Z5duXbaOqFT0IDuXb0o0n6J1xX_kA/view?usp=drive_link', 'https://drive.google.com/file/d/1p--XO0qq1MZFB1gYsre6D4z9iUGNr3Dv/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, material_finish, mounting, adjustment_dial, certifications, lead_time, cut_sheet, ip_rating) VALUES ('LED Linear Series', 'Light Tube T8', 'SL-DGA00-209LT-G8-H-U', '2ft', '9W', 'AC100-240V', '3000-6500k', '80', '1170lm', '130lm/w', 'White/A6063 Aluminum/PCB', 'Tube', 'Single or Double Input Optional', 'DLC ETL RoHS, LM79, LM80', '75 days', 'https://drive.google.com/file/d/1Dq1R7zrXNAeQqBhki7QcPve4agtt1VE8/view?usp=drive_link', 'https://drive.google.com/file/d/1a7-P4IGhF6_yCpk7kKmqa2Tsi4VxwG8y/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, material_finish, mounting, adjustment_dial, certifications, lead_time, cut_sheet, ip_rating) VALUES ('LED Linear Series', 'Light Tube T8', 'SL-DGA00-415LT-G8-H-U', '4ft', '15W', 'AC100-240V', '3000-6500k', '80', '1950lm', '130lm/w', 'White/A6063 Aluminum/PCB', 'Tube', 'Single or Double Input Optional', 'DLC ETL RoHS, LM79, LM80', '75 days', 'https://drive.google.com/file/d/1Dq1R7zrXNAeQqBhki7QcPve4agtt1VE8/view?usp=drive_link', 'https://drive.google.com/file/d/1a7-P4IGhF6_yCpk7kKmqa2Tsi4VxwG8y/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, sensors_and_controls, pir_microwave_bluetooth, certifications, warranty, moq, cost_thailand_vietnam) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'PVPL-M2705-40W22-02', '2x2 ft', '26/32/40W', 'AC120-277Vac', '3-6.5k, Tunable', '80', '3250/4000/5000', '125lm/w', 'Triac', 'Bi_Level', 'PIR/Microwave/Bluetooth', 'ETL DLC FCC ES T24 CP65', '5 Yr', '2,880', '$12.80 (Vietnam)');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, sensors_and_controls, pir_microwave_bluetooth, certifications, warranty, moq, cost_thailand_vietnam) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'PVPL-M2705-40W14-02', '1x4 ft', '26/32/40W', 'AC120-277Vac', '3-6.5k, Tunable', '80', '3250/4000/5000', '125lm/w', 'Triac', 'Bi_Level', 'PIR/Microwave/Bluetooth', 'ETL DLC FCC ES T24 CP65', '5 Yr', '3,360', '$13.80 (Vietnam)');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, sensors_and_controls, pir_microwave_bluetooth, certifications, warranty, moq, cost_thailand_vietnam) VALUES ('LED Panel and Troffer Series', 'Flat Panel Back Lit', 'PVPL-M2705-50W24-02', '2x4 ft', '32/40/50W', 'AC120-277Vac', '3-6.5k, Tunable', '80', '4000/5000/6250', '125lm/w', 'Triac', 'Bi_Level', 'PIR/Microwave/Bluetooth', 'ETL DLC FCC ES T24 CP65', '5 Yr', '1,440', '$18.80 (Vietnam)');