

INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', false, false, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', false, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', true, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', true, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', false, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', false, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', true, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', true, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-4FT-LS100-3W3CCT', '4ft', '20W/30W/40W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '2600/3900/5200LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', false, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', false, false, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', false, true, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', false, true, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', false, false, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', false, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', true, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', true, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', 'B-Level', 'PIR', false, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', false, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', true, 'Surface/Suspension/Linkable', 'no kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', true, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo) VALUES ('LED Linear Series', 'Strip Light', 'ARVL-HY-8FT-LS100-3W3CCT', '8ft', '40/W/50W/60W', 'AC120-277Vac', '4/5/6k (Tunable)', '80', '5200/6500/7800LM', '130lm/w', '0-10V', 'White-Aluminum', 'Occupancy', 'PIR', false, 'Surface/Suspension/Linkable', 'Linkable Kit', 'ETL DLC', '85 days', 'https://drive.google.com/file/d/1UTYDedvNpiqThigj4wilkzc0ZPruDk0b/view?usp=drive_link', '5 yr', '500', '$13.90 (Ningbo)', 'https://drive.google.com/file/d/1mGyCUK3cVz0m13EJzGd-XIVn6vQaO3J9/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, false, true, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, false, true, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, true, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, true, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, true, false, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, true, false, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, true, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, true, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, true, false, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, true, false, true, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, true, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, true, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, true, true, false, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, true, true, true, false, 'Surface/Suspension/Continuous', true, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, remote_control, plugin_sensor, emergency_backup_battery, junction_cover, mounting, installation_kits, certifications, lead_time, cut_sheet, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo) VALUES ('LED Linear Series', 'Strip Light', 'DM-ST2FT24WT-35G5K-[blank, EM, MS, ES]', '2ft', '10w/15w/24w', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '1300/1950/3120LM', '130lm/w', '0-10V', 'White/Metal/PVC', false, false, true, true, true, 'Surface/Suspension/Continuous', false, 'ETL DLC Premium', '75 days', 'https://drive.google.com/file/d/1KIAA4R1h68OPsnqewllPdU8l2Qu4B0jm/view?usp=drive_link', 'TBN', '$11.92 (DDP)', '$12.30 (DDP)', 'https://drive.google.com/file/d/12kBc5RnM-hegmKXhNcros0q9kACMNquy/view?usp=sharing');