

INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT80WT-3545k', '8ft', '50W/65W/80W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '7500/9750/12000LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT80WT-3545k', '8ft', '50W/65W/80W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '7500/9750/12000LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT80WT-3545k', '8ft', '50W/65W/80W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '7500/9750/12000LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT80WT-3545k', '8ft', '50W/65W/80W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '7500/9750/12000LM', '150lm/w', '0-10v', 'White/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT80WT-3545k', '8ft', '50W/65W/80W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '7500/9750/12000LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED Linear Series', 'LED Vapor Proof Linear Light', 'DM-VP8FT80WT-3545k', '8ft', '50W/65W/80W switchable', 'AC100-277Vac', '3.5/4/5k (Tunable)', '80', '7500/9750/12000LM', '150lm/w', '0-10v', 'White/Metal/IP65', false, true, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1ibv2olG-FT8fVuh8-B7eLBndRnacgGar/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1DK8YwzXP-KZ8hsJbNoI8xWV2PUUrut0s/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-160W-R090-C', '10.7x6.3in', '160W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '25600LM', '160lm/w', '0-10v', 'Black/Aluminum/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Suspension/Bracket', false, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$23.83', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-160W-R090-C', '10.7x6.3in', '160W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '25600LM', '160lm/w', '0-10v', 'Black/Aluminum/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Suspension/Bracket', true, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$23.83', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-160W-R090-C', '10.7x6.3in', '160W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '25600LM', '160lm/w', '0-10v', 'Black/Aluminum/IP65', false, false, 'Suspension/Bracket', true, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$23.83', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-160W-R090-C', '10.7x6.3in', '160W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '25600LM', '160lm/w', '0-10v', 'Black/Aluminum/IP65', false, false, 'Suspension/Bracket', false, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$23.83', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-160W-R090-C', '10.7x6.3in', '160W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '25600LM', '160lm/w', '0-10v', 'Black/Aluminum/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Suspension/Bracket', false, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$23.83', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-160W-R090-C', '10.7x6.3in', '160W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '25600LM', '160lm/w', '0-10v', 'Black/Aluminum/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Suspension/Bracket', true, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$23.83', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-160W-R090-C', '10.7x6.3in', '160W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '25600LM', '160lm/w', '0-10v', 'Black/Aluminum/IP65', false, true, 'Suspension/Bracket', true, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$23.83', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-160W-R090-C', '10.7x6.3in', '160W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '25600LM', '160lm/w', '0-10v', 'Black/Aluminum/IP65', false, true, 'Suspension/Bracket', false, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$23.83', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-205W-R090-C', '10.7x6.3in', '205W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '42,025LM', '205lm/w', '0-10v', 'Black/Aluminum/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Suspension/Bracket', false, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$26.95', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-205W-R090-C', '10.7x6.3in', '205W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '42,025LM', '205lm/w', '0-10v', 'Black/Aluminum/IP65', 'Occupancy', 'Microwave/Bluetooth', true, 'Suspension/Bracket', true, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$26.95', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-205W-R090-C', '10.7x6.3in', '205W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '42,025LM', '205lm/w', '0-10v', 'Black/Aluminum/IP65', false, false, 'Suspension/Bracket', true, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$26.95', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-205W-R090-C', '10.7x6.3in', '205W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '42,025LM', '205lm/w', '0-10v', 'Black/Aluminum/IP65', false, false, 'Suspension/Bracket', false, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$26.95', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-205W-R090-C', '10.7x6.3in', '205W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '42,025LM', '205lm/w', '0-10v', 'Black/Aluminum/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Suspension/Bracket', false, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$26.95', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-205W-R090-C', '10.7x6.3in', '205W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '42,025LM', '205lm/w', '0-10v', 'Black/Aluminum/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Suspension/Bracket', true, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$26.95', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-205W-R090-C', '10.7x6.3in', '205W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '42,025LM', '205lm/w', '0-10v', 'Black/Aluminum/IP65', false, true, 'Suspension/Bracket', true, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$26.95', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, plugin_sensor, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'SL-UFOA00-205W-R090-C', '10.7x6.3in', '205W', 'AC100-277Vac', '3/4/5k (Tunable)', '80', '42,025LM', '205lm/w', '0-10v', 'Black/Aluminum/IP65', false, true, 'Suspension/Bracket', false, 'UL DLC', '85 days', 'https://drive.google.com/file/d/1w3XWSu3B-o-46awpP6eeXyRHp0dBE-dt/view?usp=drive_link', '5 year', '5000', '$26.95', 'https://drive.google.com/file/d/13DL1-VBSQYe8EjWOThbvHqALjSZ62iD8/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF80/100/150W-BNN45', '12.8in', '80W/100W/150W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '13200/16500/24750LM', '165lm/w', '0-10v', 'Black/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', '30/40W', 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF80/100/150W-BNN45', '12.8in', '80W/100W/150W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '13200/16500/24750LM', '165lm/w', '0-10v', 'Black/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', '30/40W', 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF80/100/150W-BNN45', '12.8in', '80W/100W/150W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '13200/16500/24750LM', '165lm/w', '0-10v', 'Black/Metal/IP65', false, false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF80/100/150W-BNN45', '12.8in', '80W/100W/150W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '13200/16500/24750LM', '165lm/w', '0-10v', 'Black/Metal/IP65', false, false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF80/100/150W-BNN45', '12.8in', '80W/100W/150W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '13200/16500/24750LM', '165lm/w', '0-10v', 'Black/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF80/100/150W-BNN45', '12.8in', '80W/100W/150W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '13200/16500/24750LM', '165lm/w', '0-10v', 'Black/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF80/100/150W-BNN45', '12.8in', '80W/100W/150W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '13200/16500/24750LM', '165lm/w', '0-10v', 'Black/Metal/IP65', false, '30/40W', 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF80/100/150W-BNN45', '12.8in', '80W/100W/150W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '13200/16500/24750LM', '165lm/w', '0-10v', 'Black/Metal/IP65', false, '30/40W', 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF150/200/240W-BNN45', '14.4in', '150W/200W/240W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '165lm/w', '0-10v', 'Black/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', '30/40W', 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF150/200/240W-BNN45', '14.4in', '150W/200W/240W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '165lm/w', '0-10v', 'Black/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', '30/40W', 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF150/200/240W-BNN45', '14.4in', '150W/200W/240W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '165lm/w', '0-10v', 'Black/Metal/IP65', false, false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF150/200/240W-BNN45', '14.4in', '150W/200W/240W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '165lm/w', '0-10v', 'Black/Metal/IP65', false, false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF150/200/240W-BNN45', '14.4in', '150W/200W/240W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '165lm/w', '0-10v', 'Black/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, pir_microwave_bluetooth, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF150/200/240W-BNN45', '14.4in', '150W/200W/240W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '165lm/w', '0-10v', 'Black/Metal/IP65', 'Occupancy', 'Microwave/Bluetooth', false, 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF150/200/240W-BNN45', '14.4in', '150W/200W/240W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '165lm/w', '0-10v', 'Black/Metal/IP65', false, '30/40W', 'Surface/Suspension/Continious', true, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, efficacy_lumen_per_w, dimming_type, material_finish, sensors_and_controls, emergency_backup_battery, mounting, installation_kits, certifications, lead_time, cut_sheet, warranty, moq, cost_china_ddp_usa, cost_thailand_vietnam, photo, ip_rating) VALUES ('LED High Bay Series', 'High Bay UFO', 'DM-UF150/200/240W-BNN45', '14.4in', '150W/200W/240W switchable', 'AC100-277Vac', '4/5k (Tunable)', '80', '165lm/w', '0-10v', 'Black/Metal/IP65', false, '30/40W', 'Surface/Suspension/Continious', false, 'ETL DLC', '75 days', 'https://drive.google.com/file/d/1MfnWZQWw4c87kIOurFAbpv0K5Yja3eC-/view?usp=drive_link', '5 year', 'TBN', '$53.71 (DDP)', '$55.43 (DDP)', 'https://drive.google.com/file/d/1h6fjG77amALrssG_FinVXU3aJSqMIu9I/view?usp=sharing', 'IP65');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, certifications, warranty, moq, cost_thailand_vietnam) VALUES ('LED High Bay Series', 'High Bay UFO', 'PVHB-UFO02-150W-01', '10.7x6.3in', '100/125/150W', 'AC120-277V', '3.5/4/5k (Tunable)', '80', '14k/17.5k/21k', '140lm/w', 'UL DLC', '5 year', '2000', '$37.61(Vietnam)');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cct, cri_ra, lumen, efficacy_lumen_per_w, certifications, warranty, moq, cost_thailand_vietnam) VALUES ('LED High Bay Series', 'High Bay UFO', 'PVHB-UFO02-200W-01', '10.7x6.3in', '150/175/200W', 'AC120-277V', '3.5/4/5k (Tunable)', '80', '21k/24.5k/28k', '140lm/w', 'UL DLC', '5 year', '2000', '$43.89(Vietnam)');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cri_ra, lumen, efficacy_lumen_per_w, certifications, lead_time, warranty, moq, cost_china_ddp_usa) VALUES ('LED Lamps and Bulbs', 'A19 LED Bulb', 'TG-A19-8W-5000K-E26-RA80 60HZ', 'A19/E26', '8W', 'AC120', '80', '640lm', '80lm/w', 'ETL', '85 days', '3 Yr', '10,000', '$0.23 (Ningbo)');


INSERT INTO indoor_products_v2 (sub_category, product_name, model_number, size, power_w, voltage, cri_ra, lumen, efficacy_lumen_per_w, certifications, lead_time, warranty, moq, cost_china_ddp_usa) VALUES ('LED Lamps and Bulbs', 'A19 LED Bulb', 'TG-A19-13W-2700K-E26-RA80 60HZ', 'A19/E26', '13W', 'AC120', '80', '1170lm', '90lm/w', 'ETL', '85 days', '3 Yr', '10,000', '$0.32 (Ningbo)');